repos:
  # Other file formatting, plus common Git mistakes & text file standardization:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files # Don't accidentally commit giant files.
      - id: check-merge-conflict # Watch for lingering merge markers.
      - id: check-yaml # Validate all YAML files.
      - id: check-case-conflict # Avoid case sensitivity in file names.
      - id: debug-statements # Watch for lingering debugger calls.
      - id: end-of-file-fixer # Ensure there's a newline at EOF.
      - id: mixed-line-ending # Only newlines, no line-feeds.
      - id: trailing-whitespace # Remove trailing whitespace.
      - id: requirements-txt-fixer # Sorts the lines in requirements.txt
      - id: check-json # Checks json files for parseable syntax.
